import {
  Column,
  CreateDateColumn,
  Entity,
  Index,
  PrimaryGeneratedColumn,
} from 'typeorm';
import { StaffLocationPlatform } from './staff-location.enums';

@Entity('staff_location_point')
@Index('IDX_staff_location_point_session_recorded', [
  'sessionId',
  'recordedAt',
])
@Index('IDX_staff_location_point_user_recorded', [
  'staffUserId',
  'recordedAt',
])
@Index('IDX_staff_location_point_received', ['receivedAt'])
@Index('IDX_staff_location_point_session_sequence', [
  'sessionId',
  'sequenceNumber',
])
export class StaffLocationPoint {
  @PrimaryGeneratedColumn('increment', {
    type: 'bigint',
  })
  id: string;

  @Column({ type: 'int' })
  sessionId: number;

  @Column({ type: 'int' })
  staffUserId: number;

  /**
   * Sequence number generated by the device for the current session.
   * It helps preserve order and reject duplicate offline-sync points.
   */
  @Column({ type: 'bigint' })
  sequenceNumber: string;

  @Column({ type: 'double precision' })
  latitude: number;

  @Column({ type: 'double precision' })
  longitude: number;

  @Column({ type: 'double precision', nullable: true })
  accuracyMetres: number | null;

  @Column({ type: 'double precision', nullable: true })
  altitudeMetres: number | null;

  @Column({ type: 'double precision', nullable: true })
  altitudeAccuracyMetres: number | null;

  @Column({ type: 'double precision', nullable: true })
  speedMetresPerSecond: number | null;

  @Column({ type: 'double precision', nullable: true })
  headingDegrees: number | null;

  @Column({ type: 'smallint', nullable: true })
  batteryPercentage: number | null;

  @Column({ type: 'boolean', default: false })
  isCharging: boolean;

  @Column({ type: 'boolean', default: false })
  isMockLocation: boolean;

  /**
   * True when the device saved the point offline and uploaded it later.
   */
  @Column({ type: 'boolean', default: false })
  wasRecordedOffline: boolean;

  @Column({
    type: 'enum',
    enum: StaffLocationPlatform,
    default: StaffLocationPlatform.UNKNOWN,
  })
  platform: StaffLocationPlatform;

  @Column({ type: 'varchar', length: 200, nullable: true })
  deviceId: string | null;

  /**
   * Time at which the phone captured the coordinate.
   */
  @Column({ type: 'timestamptz' })
  recordedAt: Date;

  /**
   * Time at which the backend received the coordinate.
   */
  @Column({ type: 'timestamptz' })
  receivedAt: Date;

  @CreateDateColumn({ type: 'timestamptz' })
  createdAt: Date;
}