export enum StaffLocationTrackingStatus {
  REQUEST_PENDING = 'REQUEST_PENDING',
  STARTING = 'STARTING',
  LIVE = 'LIVE',
  DELAYED = 'DELAYED',
  GPS_DISABLED = 'GPS_DISABLED',
  PERMISSION_DENIED = 'PERMISSION_DENIED',
  PERMISSION_RESTRICTED = 'PERMISSION_RESTRICTED',
  DEVICE_OFFLINE = 'DEVICE_OFFLINE',
  APP_BACKGROUND_RESTRICTED = 'APP_BACKGROUND_RESTRICTED',
  APP_STOPPED = 'APP_STOPPED',
  STOPPED_BY_OWNER = 'STOPPED_BY_OWNER',
  STOPPED_BY_STAFF = 'STOPPED_BY_STAFF',
  SESSION_EXPIRED = 'SESSION_EXPIRED',
  COMPLETED = 'COMPLETED',
}

export enum StaffLocationPlatform {
  ANDROID = 'ANDROID',
  WEB = 'WEB',
  IOS = 'IOS',
  UNKNOWN = 'UNKNOWN',
}

export enum StaffLocationPermissionStatus {
  UNKNOWN = 'UNKNOWN',
  PROMPT = 'PROMPT',
  GRANTED = 'GRANTED',
  LIMITED = 'LIMITED',
  DENIED = 'DENIED',
  RESTRICTED = 'RESTRICTED',
}

export enum StaffLocationGpsStatus {
  UNKNOWN = 'UNKNOWN',
  ENABLED = 'ENABLED',
  DISABLED = 'DISABLED',
}

export enum StaffLocationNetworkStatus {
  UNKNOWN = 'UNKNOWN',
  ONLINE = 'ONLINE',
  OFFLINE = 'OFFLINE',
}

export enum StaffLocationStopReason {
  OWNER_STOPPED = 'OWNER_STOPPED',
  STAFF_STOPPED = 'STAFF_STOPPED',
  PERMISSION_REMOVED = 'PERMISSION_REMOVED',
  GPS_DISABLED = 'GPS_DISABLED',
  DEVICE_OFFLINE = 'DEVICE_OFFLINE',
  APP_STOPPED = 'APP_STOPPED',
  SESSION_EXPIRED = 'SESSION_EXPIRED',
  SYSTEM_STOPPED = 'SYSTEM_STOPPED',
  COMPLETED = 'COMPLETED',
}

export enum StaffLocationEventType {
  TRACKING_REQUESTED = 'TRACKING_REQUESTED',
  REQUEST_OPENED = 'REQUEST_OPENED',
  REQUEST_ACCEPTED = 'REQUEST_ACCEPTED',
  REQUEST_REJECTED = 'REQUEST_REJECTED',

  TRACKING_STARTING = 'TRACKING_STARTING',
  TRACKING_STARTED = 'TRACKING_STARTED',
  TRACKING_STOPPED = 'TRACKING_STOPPED',
  TRACKING_EXPIRED = 'TRACKING_EXPIRED',

  LOCATION_RECEIVED = 'LOCATION_RECEIVED',
  LOCATION_DELAYED = 'LOCATION_DELAYED',
  LOCATION_RESTORED = 'LOCATION_RESTORED',

  GPS_ENABLED = 'GPS_ENABLED',
  GPS_DISABLED = 'GPS_DISABLED',

  PERMISSION_GRANTED = 'PERMISSION_GRANTED',
  PERMISSION_DENIED = 'PERMISSION_DENIED',
  PERMISSION_RESTRICTED = 'PERMISSION_RESTRICTED',

  DEVICE_ONLINE = 'DEVICE_ONLINE',
  DEVICE_OFFLINE = 'DEVICE_OFFLINE',

  APP_ACTIVE = 'APP_ACTIVE',
  APP_BACKGROUND = 'APP_BACKGROUND',
  APP_STOPPED = 'APP_STOPPED',
  BACKGROUND_RESTRICTED = 'BACKGROUND_RESTRICTED',

  HEARTBEAT_RECEIVED = 'HEARTBEAT_RECEIVED',
  OFFLINE_POINTS_SYNCED = 'OFFLINE_POINTS_SYNCED',

  BATTERY_LOW = 'BATTERY_LOW',
  MOCK_LOCATION_DETECTED = 'MOCK_LOCATION_DETECTED',

  OWNER_ACTION = 'OWNER_ACTION',
  SYSTEM_ACTION = 'SYSTEM_ACTION',
}