import {
  Column,
  CreateDateColumn,
  Entity,
  Index,
  PrimaryGeneratedColumn,
  UpdateDateColumn,
} from 'typeorm';
import {
  StaffLocationGpsStatus,
  StaffLocationNetworkStatus,
  StaffLocationPermissionStatus,
  StaffLocationPlatform,
  StaffLocationStopReason,
  StaffLocationTrackingStatus,
} from './staff-location.enums';

@Entity('staff_location_tracking_session')
@Index('IDX_staff_location_session_user_created', [
  'staffUserId',
  'createdAt',
])
@Index('IDX_staff_location_session_status_active', ['status', 'isActive'])
@Index('IDX_staff_location_session_requested_by', [
  'requestedByUserId',
  'requestedAt',
])
@Index('IDX_staff_location_session_last_location', ['lastLocationAt'])
@Index('IDX_staff_location_session_last_heartbeat', ['lastHeartbeatAt'])
export class StaffLocationTrackingSession {
  @PrimaryGeneratedColumn()
  id: number;

  /**
   * Staff member whose location is being tracked.
   *
   * We intentionally store the numeric ID without adding an ORM relation here.
   * This keeps the new module isolated from the existing User entity and avoids
   * changing existing user deletion, hiding, or loading behaviour.
   */
  @Column({ type: 'int' })
  staffUserId: number;

  /**
   * OWNER/developer user who requested this tracking session.
   */
  @Column({ type: 'int' })
  requestedByUserId: number;

  /**
   * User who stopped the session.
   * Null when the session is still active or ended automatically.
   */
  @Column({ type: 'int', nullable: true })
  stoppedByUserId: number | null;

  @Column({
    type: 'enum',
    enum: StaffLocationTrackingStatus,
    default: StaffLocationTrackingStatus.REQUEST_PENDING,
  })
  status: StaffLocationTrackingStatus;

  @Column({
    type: 'enum',
    enum: StaffLocationPlatform,
    default: StaffLocationPlatform.UNKNOWN,
  })
  platform: StaffLocationPlatform;

  @Column({
    type: 'enum',
    enum: StaffLocationPermissionStatus,
    default: StaffLocationPermissionStatus.UNKNOWN,
  })
  permissionStatus: StaffLocationPermissionStatus;

  @Column({
    type: 'enum',
    enum: StaffLocationGpsStatus,
    default: StaffLocationGpsStatus.UNKNOWN,
  })
  gpsStatus: StaffLocationGpsStatus;

  @Column({
    type: 'enum',
    enum: StaffLocationNetworkStatus,
    default: StaffLocationNetworkStatus.UNKNOWN,
  })
  networkStatus: StaffLocationNetworkStatus;

  /**
   * A stable installation/device identifier generated by our application.
   * It must not be an Android hardware identifier.
   */
  @Column({ type: 'varchar', length: 200, nullable: true })
  deviceId: string | null;

  @Column({ type: 'varchar', length: 100, nullable: true })
  appVersion: string | null;

  @Column({ type: 'varchar', length: 100, nullable: true })
  operatingSystemVersion: string | null;

  @Column({ type: 'boolean', default: true })
  isActive: boolean;

  /**
   * True after the staff app has opened the tracking request.
   */
  @Column({ type: 'boolean', default: false })
  requestOpened: boolean;

  /**
   * True after the staff member accepts the request.
   */
  @Column({ type: 'boolean', default: false })
  requestAccepted: boolean;

  @Column({ type: 'timestamptz', nullable: true })
  requestedAt: Date | null;

  @Column({ type: 'timestamptz', nullable: true })
  requestOpenedAt: Date | null;

  @Column({ type: 'timestamptz', nullable: true })
  acceptedAt: Date | null;

  @Column({ type: 'timestamptz', nullable: true })
  startedAt: Date | null;

  @Column({ type: 'timestamptz', nullable: true })
  stoppedAt: Date | null;

  @Column({ type: 'timestamptz', nullable: true })
  lastLocationAt: Date | null;

  @Column({ type: 'timestamptz', nullable: true })
  lastHeartbeatAt: Date | null;

  @Column({ type: 'timestamptz', nullable: true })
  lastStatusChangeAt: Date | null;

  /**
   * Latest known coordinate duplicated on the session.
   *
   * This is intentional. The live dashboard can load one row per employee
   * without scanning the potentially large location-points table.
   */
  @Column({ type: 'double precision', nullable: true })
  lastLatitude: number | null;

  @Column({ type: 'double precision', nullable: true })
  lastLongitude: number | null;

  @Column({ type: 'double precision', nullable: true })
  lastAccuracyMetres: number | null;

  @Column({ type: 'double precision', nullable: true })
  lastSpeedMetresPerSecond: number | null;

  @Column({ type: 'double precision', nullable: true })
  lastHeadingDegrees: number | null;

  @Column({ type: 'smallint', nullable: true })
  batteryPercentage: number | null;

  @Column({ type: 'boolean', default: false })
  isCharging: boolean;

  @Column({ type: 'boolean', default: false })
  isMockLocationDetected: boolean;

  /**
   * Approximate total distance calculated incrementally.
   * This prevents recalculating the complete route for every list request.
   */
  @Column({
    type: 'double precision',
    default: 0,
  })
  totalDistanceMetres: number;

  @Column({
    type: 'enum',
    enum: StaffLocationStopReason,
    nullable: true,
  })
  stopReason: StaffLocationStopReason | null;

  /**
   * Human-readable current problem shown to the OWNER.
   *
   * Examples:
   * "GPS switched off"
   * "Location permission denied"
   * "Device heartbeat not received"
   */
  @Column({ type: 'varchar', length: 500, nullable: true })
  currentFailureMessage: string | null;

  /**
   * Device-generated tracking error code for diagnostics.
   */
  @Column({ type: 'varchar', length: 100, nullable: true })
  currentFailureCode: string | null;

  /**
   * Optional OWNER remark entered when requesting tracking.
   */
  @Column({ type: 'varchar', length: 500, nullable: true })
  requestRemark: string | null;

  /**
   * Set when sessions are hidden from normal history.
   * We preserve the CRM's hide/restore standard.
   */
  @Column({ type: 'boolean', default: false })
  isHidden: boolean;

  @Column({ type: 'int', nullable: true })
  hiddenByUserId: number | null;

  @Column({ type: 'timestamptz', nullable: true })
  hiddenAt: Date | null;

  @CreateDateColumn({ type: 'timestamptz' })
  createdAt: Date;

  @UpdateDateColumn({ type: 'timestamptz' })
  updatedAt: Date;
}