import {
  ArrayMaxSize,
  ArrayMinSize,
  IsArray,
  IsBoolean,
  IsDateString,
  IsEnum,
  IsInt,
  IsNumber,
  IsOptional,
  IsString,
  Max,
  MaxLength,
  Min,
  ValidateNested,
} from 'class-validator';
import { Type } from 'class-transformer';
import { StaffLocationPlatform } from '../staff-location.enums';

export class StaffLocationPointDto {
  /**
   * Session-local sequence number generated by the device.
   * Must continuously increase for each tracking session.
   */
  @IsInt()
  @Min(1)
  sequenceNumber: number;

  @IsNumber()
  @Min(-90)
  @Max(90)
  latitude: number;

  @IsNumber()
  @Min(-180)
  @Max(180)
  longitude: number;

  @IsOptional()
  @IsNumber()
  @Min(0)
  accuracyMetres?: number;

  @IsOptional()
  @IsNumber()
  altitudeMetres?: number;

  @IsOptional()
  @IsNumber()
  @Min(0)
  altitudeAccuracyMetres?: number;

  @IsOptional()
  @IsNumber()
  @Min(0)
  speedMetresPerSecond?: number;

  @IsOptional()
  @IsNumber()
  @Min(0)
  @Max(360)
  headingDegrees?: number;

  @IsOptional()
  @IsInt()
  @Min(0)
  @Max(100)
  batteryPercentage?: number;

  @IsOptional()
  @IsBoolean()
  isCharging?: boolean;

  @IsOptional()
  @IsBoolean()
  isMockLocation?: boolean;

  @IsOptional()
  @IsBoolean()
  wasRecordedOffline?: boolean;

  @IsDateString()
  recordedAt: string;
}

export class StaffLocationPointBatchDto {
  @IsEnum(StaffLocationPlatform)
  platform: StaffLocationPlatform;

  @IsOptional()
  @IsString()
  @MaxLength(200)
  deviceId?: string;

  /**
   * Maximum 100 points in one request.
   *
   * This is large enough for offline synchronization but bounded to prevent
   * excessive request size and database work.
   */
  @IsArray()
  @ArrayMinSize(1)
  @ArrayMaxSize(100)
  @ValidateNested({ each: true })
  @Type(() => StaffLocationPointDto)
  points: StaffLocationPointDto[];
}